CREATE DATABASE dbzapateria
DEFAULT CHARACTER SET utf8mb4;

USE dbzapateria;

CREATE TABLE MARCA (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1
);

CREATE TABLE TALLA (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBRE_TALLA INT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1
);

CREATE TABLE PROVEEDOR (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    RAZON_SOCIAL VARCHAR(100) NOT NULL,
    CELULAR CHAR(9),
    TELEFONO CHAR(10),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1
);

CREATE TABLE PERSONA (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DNI CHAR(8) NOT NULL,
    CELULAR CHAR(9),
    TELEFONO CHAR(10),
    DIRECCION VARCHAR(200),
    TIPO CHAR(1),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1
);

CREATE TABLE CLIENTE (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_PERSONA INT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID)
);

CREATE TABLE EMPLEADO (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_PERSONA INT NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    SUELDO DECIMAL(10,2),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(ID)
);

CREATE TABLE PRODUCTO (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_MARCA INT NOT NULL,
    ID_PROVEEDOR INT NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    STOCK INT,
    DESCRIPCION VARCHAR(300),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1,
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID)
);

CREATE TABLE PRODUCTO_TALLA (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_TALLA INT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID),
    FOREIGN KEY (ID_TALLA) REFERENCES TALLA(ID)
);

CREATE TABLE BOLETA (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID)
);

CREATE TABLE BOLETA_DETALLE (
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ID_BOLETA INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT 1,
    FOREIGN KEY (ID_BOLETA) REFERENCES BOLETA(ID),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);

